### ISSUE TITLE
Feedback on Reakit

### ISSUE THREAD

**Issue by diegohaz** [httpiago/navbar-as-splashscreen-demo#1]
Hey @httpiago

I'm following public repositories that use Reakit, including this one. I'm constantly trying to improve the library, and I think your feedback would be really valuable.

How was your experience using Reakit? How did it help you? How could it be better?

Thank you 🙏

**Comment by diegohaz** [comment]
Also, I'd suggest you to put the GitHub pages url visible next to the repository description.

**Comment by iagobruno** [comment]
I did not use it much in this project but I really liked what I saw and I will certainly use it in other projects (I'm excited to use the Dialog component). From what I seen, Reakit solves several problems in a simple way and the bonus it's super customizable.
Congratulations for all the work! 👏👏
